version: "3.9"

services:
  parrot-42:
    image: parrot/cybersec42
    container_name: parrot-42
    hostname: parrot-42
    build: ./src
    volumes:
      - /lib/modules:/lib/modules:ro
      - ~/Cybersec42:/work
    networks:
      - parrot-42
    ports:
      - "22:2222"
    environment:
      - ROC_ENABLE_PRE_VEGA=1
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

networks:
  parrot-42:
    driver: bridge

